Repository rust-ndarray/ndarray, pull requests merged in 2018-11, with the labels that each got.

#527 Add table of conversions to/from Vecs and slices
  src/lib.rs
Labels: A-docs

#531 Add headings for more sections in ArrayBase docs
  src/impl_1d.rs
  src/impl_2d.rs
  src/lib.rs
  src/numeric/impl_numeric.rs
Labels: A-docs

#536 Add missing conversions to Conversions docs
  src/lib.rs
Labels: A-docs

#540 Update README with changes since 0.12.0
  README.rst
Labels: A-docs

#535 Add into_scalar method for Array0
  src/impl_owned_array.rs
  src/lib.rs
  tests/array.rs
Labels: enhancement

#547 Implement Iterator::rfold where we can
  benches/iter.rs
  src/iterators/mod.rs
  tests/iterators.rs
Labels: enhancement

#537 Rework subview methods and other related methods
  examples/axis_ops.rs
  examples/sort-axis.rs
  serialization-tests/tests/serialize.rs
  src/dimension/mod.rs
  src/doc/ndarray_for_numpy_users/mod.rs
  src/impl_2d.rs
  src/impl_dyn.rs
  src/impl_methods.rs
  src/lib.rs
  src/numeric/impl_numeric.rs
  src/slice.rs
  tests/array.rs
  tests/dimension.rs
  tests/iterators.rs
Labels: enhancement

#544 Update ndarray-rand for rand 0.6
  ndarray-rand/Cargo.toml
  ndarray-rand/README.rst
  ndarray-rand/benches/bench.rs
  ndarray-rand/src/lib.rs
  ndarray-rand/tests/tests.rs
  numeric-tests/Cargo.toml
Labels: breaking-change

#477 Attempt to document usage of ref in azip
  src/zip/zipmacro.rs
Labels: A-docs

#550 Fix .axis_chunks_iter/_mut() for zero stride and zero sized types
  benches/iter.rs
  src/impl_methods.rs
  src/iterators/mod.rs
  src/zip/mod.rs
  tests/iterators.rs
Labels: bug

#517 Bump to Rust 1.30, add macros to preludes, and switch macro_use to use
  .travis.yml
  benches/bench1.rs
  benches/chunks.rs
  benches/construct.rs
  benches/higher-order.rs
  benches/iter.rs
  blas-tests/tests/oper.rs
  examples/axis_ops.rs
  examples/column_standardize.rs
  examples/convo.rs
  examples/life.rs
  examples/rollaxis.rs
  examples/zip_many.rs
  numeric-tests/tests/accuracy.rs
  parallel/benches/rayon.rs
  parallel/src/lib.rs
  parallel/src/zipmacro.rs
  parallel/tests/azip.rs
  parallel/tests/rayon.rs
  serialization-tests/tests/serialize.rs
  src/dimension/dimension_trait.rs
  src/dimension/mod.rs
  src/doc/ndarray_for_numpy_users/coord_transform.rs
  src/doc/ndarray_for_numpy_users/mod.rs
  src/doc/ndarray_for_numpy_users/rk_step.rs
  src/doc/ndarray_for_numpy_users/simple_math.rs
  src/free_functions.rs
  src/impl_constructors.rs
  src/impl_methods.rs
  src/lib.rs
  src/prelude.rs
  src/slice.rs
  src/stacking.rs
  src/zip/zipmacro.rs
  tests/array-construct.rs
  tests/array.rs
  tests/azip.rs
  tests/dimension.rs
  tests/iterator_chunks.rs
  tests/iterators.rs
  tests/oper.rs
  tests/s.rs
  tests/stacking.rs
  tests/windows.rs
Labels: breaking-change

#560 Add ArcArray to the prelude and activate the deprecation on RcArray
  src/aliases.rs
  src/lib.rs
  src/prelude.rs
  tests/array-construct.rs
  tests/array.rs
  tests/broadcast.rs
  tests/dimension.rs
  tests/iterators.rs
  tests/oper.rs
  tests/zst.rs
Labels: breaking-change

#556 Update matrixmultiply dependency to 0.2
  Cargo.toml
Labels: breaking-change, performance

#515 Adjust constraints on ddof for var_axis and std_axis
  src/numeric/impl_numeric.rs
  tests/array.rs
Labels: breaking-change, enhancement

#557 Remove rustc-serialize crate feature
  Cargo.toml
  README.rst
  serialization-tests/Cargo.toml
  serialization-tests/tests/serialize.rs
  src/array_serialize.rs
  src/arraytraits.rs
  src/lib.rs
Labels: breaking-change

#496 Add raw array pointer types
  src/data_traits.rs
  src/dimension/mod.rs
  src/impl_1d.rs
  src/impl_2d.rs
  src/impl_clone.rs
  src/impl_methods.rs
  src/impl_raw_views.rs
  src/impl_views.rs
  src/lib.rs
  src/prelude.rs
Labels: enhancement
