Repository rust-ndarray/ndarray, pull requests merged in 2019-07, with the labels that each got.

#656 Fix docs for ArrayViewMut -> &mut [A] conversion
  src/lib.rs
Labels: A-docs

#648 Use FromIterator trait rather than custom method
  benches/higher-order.rs
  blas-tests/tests/oper.rs
  examples/life.rs
  src/arraytraits.rs
  src/free_functions.rs
  src/impl_constructors.rs
  src/impl_methods.rs
  src/slice.rs
  tests/array.rs
  tests/azip.rs
  tests/broadcast.rs
  tests/iterators.rs
  tests/ix0.rs
  tests/ixdyn.rs
  tests/oper.rs
  tests/windows.rs
Labels: breaking-change

#659 Upgrade to rand 0.7.0
  .travis.yml
  ndarray-rand/Cargo.toml
  ndarray-rand/README.rst
  ndarray-rand/benches/bench.rs
  ndarray-rand/src/lib.rs
  numeric-tests/Cargo.toml
  numeric-tests/tests/accuracy.rs
  src/lib.rs
Labels: ndarray-rand
