Repository rust-ndarray/ndarray, pull requests merged in 2019-04, with the labels that each got.

#612 Support zero-length `axis` in `.map_axis/_mut()`
  Cargo.toml
  src/impl_methods.rs
  tests/array.rs
Labels: enhancement

#614 Forward more iterator methods
  src/iterators/mod.rs
Labels: enhancement, performance

#613 Add safety check for size after broadcasting
  src/impl_methods.rs
Labels: bug

#615 Implement Zip::all()
  src/zip/mod.rs
  tests/azip.rs
Labels: enhancement
