Repository rust-ndarray/ndarray, pull requests merged in 2019-05, with the labels that each got.

#588 Allow ops on arrays with elems of different types
  src/arraytraits.rs
  src/impl_ops.rs
  src/numeric_util.rs
  tests/iterators.rs
Labels: breaking-change, enhancement

#581 Implement approx traits for ArrayBase
  Cargo.toml
  src/array_approx.rs
  src/doc/ndarray_for_numpy_users/mod.rs
  src/geomspace.rs
  src/impl_constructors.rs
  src/impl_methods.rs
  src/lib.rs
  src/logspace.rs
  src/numeric/impl_numeric.rs
  tests/array-construct.rs
  tests/array.rs
  tests/azip.rs
  tests/numeric.rs
  tests/par_azip.rs
  tests/par_rayon.rs
Labels: enhancement

#634 Basic traits restrictions for Dimension::Pattern
  src/dimension/dimension_trait.rs
Labels: enhancement

#636 Fix slice offset computation for special cases
  src/dimension/mod.rs
  tests/array.rs
Labels: bug

#632 CowArray feature
  src/data_traits.rs
  src/doc/ndarray_for_numpy_users/mod.rs
  src/impl_cow.rs
  src/lib.rs
  src/prelude.rs
  tests/array.rs
Labels: enhancement
