Repository rust-ndarray/ndarray, pull requests merged in 2019-09, with the labels that each got.

#565 Use box drawing art for illustrating an example for ArrayView::split_at
  src/impl_methods.rs
  src/impl_views.rs
Labels: A-docs

#684 Add .fold() method to Zip
  src/zip/mod.rs
Labels: enhancement

#585 Fix blas mat-vec multiplication on array with only 1 nontrivial dimension
  blas-tests/tests/oper.rs
  src/linalg/impl_linalg.rs
Labels: bug

#691 Add .split_at() methods for AxisChunksIter/Mut
  src/iterators/mod.rs
  tests/iterators.rs
Labels: enhancement

#686 Implement .nth_back() for iterators
  .travis.yml
  benches/iter.rs
  src/iterators/mod.rs
  tests/iterators.rs
Labels: performance

#700 Add into_scalar for ArrayView0 and ArrayViewMut0
  src/impl_views.rs
  src/impl_views/constructors.rs
  src/impl_views/conversions.rs
  src/impl_views/indexing.rs
  src/impl_views/mod.rs
  src/impl_views/splitting.rs
  tests/array.rs
Labels: enhancement

#683 Change ArrayBase.ptr to NonNull type
  Cargo.toml
  src/arraytraits.rs
  src/data_traits.rs
  src/extension.rs
  src/extension/nonnull.rs
  src/impl_clone.rs
  src/impl_constructors.rs
  src/impl_methods.rs
  src/impl_owned_array.rs
  src/impl_raw_views.rs
  src/impl_views/constructors.rs
  src/impl_views/conversions.rs
  src/iterators/mod.rs
  src/iterators/windows.rs
  src/lib.rs
  src/linalg/impl_linalg.rs
  src/zip/mod.rs
Labels: breaking-change

#626 Change syntax of azip! to be similar to for loops
  benches/bench1.rs
  benches/chunks.rs
  benches/iter.rs
  benches/par_rayon.rs
  examples/zip_many.rs
  src/doc/ndarray_for_numpy_users/coord_transform.rs
  src/numeric/impl_numeric.rs
  src/zip/zipmacro.rs
  tests/azip.rs
Labels: breaking-change, enhancement

#663 Re-export `rand` distributions
  ndarray-rand/Cargo.toml
  ndarray-rand/README.md
  ndarray-rand/README.rst
  ndarray-rand/RELEASES.md
  ndarray-rand/src/lib.rs
  ndarray-rand/tests/tests.rs
Labels: ndarray-rand

#633 Improve formatting for arrays with ndim > 2
  src/arrayformat.rs
  tests/format.rs
Labels: enhancement

#704 Docs polishing
  src/doc/ndarray_for_numpy_users/mod.rs
  src/lib.rs
Labels: A-docs

#707 Use alternate form flag (#) to disable overflow with ellipsis
  src/arrayformat.rs
Labels: enhancement

#611 Add accumulate_axis_inplace method and implement NdProducer for RawArrayView/Mut
  src/impl_methods.rs
  src/zip/mod.rs
  tests/array.rs
Labels: enhancement
