Repository rust-ndarray/ndarray, pull requests merged in 2024-03, with the labels that each got.

#1196 Fix unsafe blocks in s![] macro
  src/slice.rs
Labels: bug

#1138 Fix Miri failure with -Zmiri-tag-raw-pointers
  src/impl_methods.rs
Labels: bug

#1142 Fix Miri errors for WindowsIter and ExactChunksIter/Mut
  src/impl_views/conversions.rs
  src/iterators/chunks.rs
  src/iterators/macros.rs
  src/iterators/windows.rs
  src/lib.rs
Labels: bug

#1131 Add missing safety checks to `From<&[[A; N]]> for ArrayView` and `From<&mut [[A; N]]> for ArrayViewMut`
  src/arraytraits.rs
  tests/array-construct.rs
Labels: bug

#1132 Make the aview0, aview1, and aview2 free functions be const fns
  .github/workflows/ci.yaml
  Cargo.toml
  scripts/all-tests.sh
  src/aliases.rs
  src/arraytraits.rs
  src/dimension/dim.rs
  src/free_functions.rs
  src/lib.rs
Labels: enhancement, breaking-change, msrv-change

#1228 Add Zip::any
  src/zip/mod.rs
Labels: enhancement

#1237 implement DoubleEndedIterator for 1d `LanesIter`
  src/iterators/mod.rs
  tests/iterators.rs
Labels: enhancement

#1211 Add slice_axis_move method
  src/impl_methods.rs
Labels: enhancement

#1130 Add additional array -> array view conversions
  src/arraytraits.rs
  tests/append.rs
Labels: enhancement
